docollective/accounts/urls.py
from django.urls import path
from .views import signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, CreateAddress, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('create-address/', CreateAddress.as_view(), name="create-address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete")
]

docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/shop/urls.py
from django.urls import path
from .views import detail_view, add_to_cart, cart_view, delete_garments_cart, delete_cart, CreateGarment, all_garments, \
    DeleteGarment, my_shop_view, validate_cart_view, address_choice_view, admin_deal_validation_view, recommendations_view, \
    admin_advert_validation_view, search_results_view

app_name = "shop"
urlpatterns = [
    path("garment/<str:slug>/<int:pk>/", detail_view, name="detail"),
    path("add-to-cart/<int:pk>/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("address-choice/", address_choice_view, name="address-choice"),
    path("validate-cart/", validate_cart_view, name="validate-cart"),
    path("delete-garments/", delete_garments_cart, name="delete-garments"),
    path("delete-cart/", delete_cart, name="delete-cart"),
    path("create-garment/", CreateGarment.as_view(), name="create"),
    path("delete-garment/<int:pk>/", DeleteGarment.as_view(), name="delete-garment"),
    path("all/", all_garments, name="all"),
    path("search/", search_results_view, name="search"),
    path("recommendations/", recommendations_view, name="recommendations"),
    path("my-shop/", my_shop_view, name="my-shop"),
    path("admin-validation/", admin_deal_validation_view, name="admin-validation"),
    path("admin-ad-validation/", admin_advert_validation_view, name="admin-advert"),
]

docollective/accounts/models.py
import iso3166
from django.contrib import messages
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models import Q

from shop.models import SIZES, Color, Garment, Cart, Order

TYPE_USER = [("h", "Homme"), ("f", "Femme"), ("nr", "Non renseigné")]


class ExChangerManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password, **kwargs):
        if not email:
            raise ValueError("email obligatoire")
        user = self.model(email=self.normalize_email(email), username=username, first_name=first_name,
                          last_name=last_name, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, first_name, last_name, password, **kwargs):
        user = self.create_user(email, username, first_name, last_name, password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        return user


class ExChanger(AbstractUser):
    email = models.EmailField(unique=True)
    type = models.CharField(max_length=10, verbose_name="Sexe", choices=TYPE_USER)
    upper_size = models.CharField(verbose_name="Taille haut du corps", choices=SIZES, max_length=10, blank=True)
    lower_size = models.CharField(verbose_name="Taille bas du corps", choices=SIZES, max_length=10, blank=True)
    foot_size = models.CharField(verbose_name="Pointure", choices=SIZES, max_length=10, blank=True)
    favorite_color = models.ForeignKey(to=Color, on_delete=models.SET_NULL, verbose_name="Couleur favorite",
                                       null=True, blank=True)

    REQUIRED_FIELDS = ["username", "first_name", "last_name"]
    USERNAME_FIELD = "email"

    objects = ExChangerManager()

    @property
    def number_adresses(self):
        number_adresses = ExChangerAdresses.objects.filter(user=self).count()
        return number_adresses

    @property
    def upper_size_property(self):
        return self.upper_size or "nc"

    @property
    def lower_size_property(self):
        return self.lower_size or "nc"

    @property
    def foot_size_property(self):
        return self.foot_size or "nc"

    @property
    def favorite_color_property(self):
        return self.favorite_color.name if self.favorite_color else "nc"

    def recommendations(self, size, category):
        """
            Generates a query for garment recommendations based on the user's preferences.

            This method filters garments that match the given size and category, are active,
            correspond to the user's type, and either contain or are associated with the user's
            favorite color.

            Args:
            size (str): The size of the garment.
            category (str): The category of the garment.

            Returns:
            QuerySet: A QuerySet of garment objects that meet the criteria.
            """
        query = Garment.objects.filter(
            Q(size=size), Q(activate=True), Q(type=self.type), Q(category=category),
            Q(description__icontains=self.favorite_color_property) | Q(
                color__name__icontains=self.favorite_color_property)
        )
        return query

    def add_to_cart(self, request, garment):
        """
           Adds a specified garment to the user's cart if it's not already in any cart.

           First checks if the garment is already in the user's cart, then checks if it is
           in any cart. If not in any cart, the garment is added to the user's cart.

           Args:
           request (HttpRequest): The HttpRequest object.
           garment (Garment): The Garment object to add to the cart.

           Returns:
           bool: True if the garment is successfully added, False otherwise.
           """
        cart, _ = Cart.objects.get_or_create(user=self)

        if cart.orders.filter(garment__id=garment.id).exists():
            messages.add_message(request, messages.WARNING, f"{garment.description} est déjà dans votre panier")
            return False

        elif Cart.objects.filter(orders__garment__id=garment.id).exists():
            messages.add_message(request, messages.WARNING, f"{garment.description} est déjà dans un panier")
            return False

        else:
            order = Order.objects.create(user=self, garment=garment)
            cart.orders.add(order)

            return True

    def _update_to_false_all_user_addresses(self):
        self.adresses.filter(default=True).update(default=False)

    def _update_to_true_address(self, pk):
        return self.adresses.filter(pk=pk).update(default=True)

    def update_default_address(self, pk):
        """
            Updates the default address of the user.

            Sets all addresses of the user to non-default and then updates the specified address
            to be the default one.

            Args:
            pk (int): The primary key of the address to be set as default.

            Returns:
            int: The number of records affected by the update operation.
            """
        self._update_to_false_all_user_addresses()
        return self._update_to_true_address(pk)


class ExChangerAdresses(models.Model):
    user: ExChanger = models.ForeignKey(to=ExChanger, on_delete=models.CASCADE, verbose_name="Utilisateur",
                                        related_name="adresses")
    name = models.CharField(max_length=200, verbose_name="Nom de l'adresse")
    address_1 = models.CharField(max_length=1024, help_text="Voirie, numéro de rue", verbose_name="Adresse 1")
    address_2 = models.CharField(max_length=1024, help_text="Bât, étage, lieu-dit", verbose_name="Adresse 2",
                                 blank=True)
    city = models.CharField(max_length=1024, verbose_name="Commune")
    zip_code = models.CharField(max_length=32, verbose_name="Code Postal")
    country = models.CharField(max_length=2, choices=[(c.alpha2.lower(), c.name) for c in iso3166.countries])
    default = models.BooleanField(default=False, verbose_name="Défaut")

    class Meta:
        verbose_name = "Adresse"

    def __str__(self):
        return f"{self.user} - {self.name}"

docollective/shop/models.py
import uuid

from django.contrib import messages
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from docollective.settings import AUTH_USER_MODEL
from shop.func.confirm_order import confirm_order

SIZES = [(str(i), str(i)) for i in range(16, 71)]
YEARS = [(str(y), str(y)) for y in range(1900, timezone.now().year + 1)]
STATE = [("b", "Bon état"), ("tb", "Très bon état"), ("cn", "Comme neuf")]
TYPE = [("h", "Homme"), ("f", "Femme"), ("e", "Enfant")]
CATEGORY = [("ch", "Chaussures"), ("pa", "Pantalons"), ("ha", "Hauts")]


def user_directory_path(instance, filename):
    return f"{instance.user.username}/{filename}"


class Garment(models.Model):
    description = models.CharField(max_length=50, verbose_name="Description", help_text="50 caractères max")
    reference = models.UUIDField(verbose_name="Référence", blank=True, default=uuid.uuid4, editable=True)
    slug = models.SlugField(blank=True)
    user = models.ForeignKey(to=AUTH_USER_MODEL, verbose_name="Utilisateur", on_delete=models.CASCADE,
                             related_name="garments")
    price = models.IntegerField(verbose_name="Prix d'achat")
    size = models.CharField(verbose_name="Taille", choices=SIZES, max_length=10)
    color = models.ForeignKey(to="Color", on_delete=models.SET_NULL, verbose_name="Couleur", null=True)
    year = models.CharField(verbose_name="Année", choices=YEARS, blank=True, max_length=4)
    category = models.CharField(verbose_name="Catégorie", choices=CATEGORY, max_length=20)
    state = models.CharField(verbose_name="Etat", choices=STATE, max_length=20)
    type = models.CharField(verbose_name="Sexe", choices=TYPE, max_length=10)
    pics_1 = models.ImageField(verbose_name="Photo 1", upload_to=user_directory_path)
    pics_2 = models.ImageField(verbose_name="Photo 2", blank=True, null=True, upload_to=user_directory_path)
    pics_3 = models.ImageField(verbose_name="Photo 3", blank=True, null=True, upload_to=user_directory_path)
    published = models.DateTimeField(verbose_name="Date de publication", auto_now_add=True)
    activate = models.BooleanField(default=False, verbose_name="Activé")
    bought = models.BooleanField(default=False, verbose_name="Acheté")

    class Meta:
        verbose_name = "Vêtement"

    def __str__(self):
        return f"{self.user} - {self.get_category_display()} - {self.description}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.description)

        if self._state.adding:
            super().save(*args, **kwargs)
            Garment.__send_email()
        else:
            super().save(*args, **kwargs)

    @staticmethod
    def __send_email():
        """
            Sends an email notification about a new announcement.

            This static method sends a predefined email with the subject 'Nouvelle annonce' and a
            message stating 'Nouvelle annonce déposée' to a specified recipient list.

            Note:
            This method is private and intended for internal use within its class.
            """
        send_mail(subject="Nouvelle annonce", message="Nouvelle annonce déposée",
                  recipient_list=["gabrieltrouve5@yahoo.com"], from_email=None)

    def get_absolute_url(self):
        # https://docs.djangoproject.com/fr/4.2/ref/models/instances/#get-absolute-url
        return reverse(viewname="shop:detail", kwargs={"slug": self.slug, "pk": self.pk})

    @property
    def garment_year(self):
        return self.year or "NC"


class Color(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=20)
    hexa = models.CharField(verbose_name="Hex", max_length=7)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.hexa.startswith('#'):
            self.hexa = "#" + self.hexa
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Couleur"


class Order(models.Model):
    user = models.ForeignKey(to=AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Utilisateur")
    garment = models.ForeignKey(to=Garment, on_delete=models.SET_NULL, null=True, verbose_name="Vêtements")
    reference = models.UUIDField(default=uuid.uuid4, editable=True, verbose_name="Référence")
    ordered = models.BooleanField(default=False, verbose_name="Commandée")
    ordered_date = models.DateTimeField(blank=True, null=True)
    validation = models.BooleanField(default=False, verbose_name="Validation du deal")

    class Meta:
        verbose_name = "Commande"

    def __str__(self):
        return f"{self.user} - {self.garment} - {self.ordered_date}"


class Cart(models.Model):
    user = models.OneToOneField(to=AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Utilisateur")
    orders = models.ManyToManyField(to=Order, verbose_name="Vêtements")
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")

    class Meta:
        verbose_name = "Panier"

    def __str__(self):
        return f"{self.user} - {self.creation_date}"

    def user_delete_cart(self):
        """
           Deletes all orders in the user's cart and then deletes the cart itself.

           This method first removes all orders associated with the cart and then proceeds to delete
           the cart instance.
           """
        self.orders.all().delete()
        self.delete()

    def validate_cart(self, request, user, address):
        """
            Validates the cart, updates orders and garments status, confirms the order, and notifies the user.

            Executes a series of internal methods to update the status of orders and garments, confirm
            the order with the given address, and send a notification to the user. After these operations,
            the cart is deleted.

            Args:
            request (HttpRequest): The HttpRequest object.
            user (User): The user object associated with the cart.
            address (Address): The address object for the order delivery.
            """
        self._update_orders_status()
        self._update_garment_status()
        self._confirm_order_and_notify_user(request, user, address)
        self.delete()

    def _update_orders_status(self):
        self.orders.all().update(ordered=True, ordered_date=timezone.now())

    def _update_garment_status(self):
        Garment.objects.filter(order__in=self.orders.all()).update(activate=False, bought=True)

    def _confirm_order_and_notify_user(self, request, user, address):
        confirm_order(user, self.orders.all(), address)
        messages.add_message(request, messages.INFO,
                             "Pour chaque vêtement demandé vous devez créer "
                             "une annonce et nous envoyer le vêtement concerné.")

docollective/shop/templates/shop/address-choice.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Choix de l'adresse{% endblock %}


{% block body %}
<div class="row mb-5">


    <div class="col">

        <div class="text-center">
            {% if default_adresse %}
            <div class="card mx-auto" style="width: 18rem;">
                <div class="card-header">
                    Adresse par défaut
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ default_adresse.name }}</li>
                    <li class="list-group-item">{{ default_adresse.address_1 }}</li>
                    {% if default_adresse.address_2 %}
                    <li class="list-group-item">{{ default_adresse.address_2 }}</li>
                    {% endif %}
                    <li class="list-group-item">{{ default_adresse.zip_code }} - {{ default_adresse.city }}</li>
                    <li class="list-group-item">{{ default_adresse.get_country_display }}</li>
                </ul>
            </div>


            {% else %}
            Pas d'adresse(s) enregistrées
            {% endif %}


        </div>

    </div>


</div>


<div class="row mb-5 justify-content-between" style="margin-top: 20px;">

    <div class="col-2">
        {% if user.adresses.all %}

        <form action="{% url 'shop:validate-cart' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Passer la commande" class="btn btn-success">
        </form>
        {% else %}
        <h4>Vous devez d'abord créer une adresse pour valider la commande</h4>
        {% endif %}
    </div>
    <div class="col-2">
        <a href="{% url 'accounts:create-address' %}" class="btn btn-outline-success">Créer une adresse</a>

    </div>
</div>
<div class="row">
    <div class="col">

        <div class="text-center">
            <p class="d-inline-flex gap-1">
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Autres adresses
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                {% for adresse in adresses %}
                <div class="card card-body mx-auto" style="margin-bottom: 20px; max-width: 300px;">
                    <!--
                    Toutes les adresses False
                    -->


                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ adresse.name }}</li>
                        <li class="list-group-item">{{ adresse.address_1 }}</li>
                        {% if adresse.address_2 %}
                        <li class="list-group-item">{{ adresse.address_2 }}</li>
                        {% endif %}
                        <li class="list-group-item">{{ adresse.zip_code }} - {{ default_adresse.city }}</li>
                        <li class="list-group-item">{{ adresse.get_country_display }}</li>
                    </ul>

                    <form action="{% url 'accounts:default_address' pk=adresse.pk %}?redirect=validate"
                          method="post">

                        {% csrf_token %}
                        <input type="submit" value="Définir" class="btn btn-outline-info">

                    </form>


                </div>
                {% endfor %}
            </div>

        </div>

    </div>
</div>
{% endblock %}

docollective/shop/templates/shop/admin-ad-validation.html
{% extends 'base.html' %}

{% block title %}Admin annonces{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Annonces en attente de validation</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">

        <form action="{% url 'shop:admin-advert' %}" method="post">
            {% csrf_token %}
            {{ forms.management_form }}


            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Validation</th>
                    <th scope="col">Date</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Description</th>
                </tr>
                </thead>
                <tbody>
                {% for form in forms %}
                <tr>
                    <th scope="row">

                        {{ form.as_p }}

                    </th>
                    <td>{{ form.instance.date }}</td>
                    <td>{{ form.instance.user }}</td>
                    <td>{{ form.instance.description }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <input type="submit" value="Valider" class="btn btn-success">
        </form>


    </div>


</div>

{% endblock %}

docollective/shop/templates/shop/admin-validation.html
{% extends 'base.html' %}

{% block title %}Admin Validation{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">En attente de validation</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">

        <form action="{% url 'shop:admin-validation' %}" method="post">
            {% csrf_token %}
            {{ forms.management_form }}


            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Validation</th>
                    <th scope="col">Date</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Numéro</th>
                </tr>
                </thead>
                <tbody>
                {% for form in forms %}
                <tr>
                    <th scope="row">

                        {{ form.as_p }}

                    </th>
                    <td>{{ form.instance.ordered_date }}</td>
                    <td>{{ form.instance.user }}</td>
                    <td>{{ form.instance.reference }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <input type="submit" value="Valider" class="btn btn-success">
        </form>


    </div>


</div>

{% endblock %}

docollective/shop/templates/shop/all.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Tous les vêtements</h2>

</div>
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center mb-5">
    <form role="search" class="d-flex">

        <input type="search" placeholder="Rechercher" aria-label="Rechercher" name="search" class="form-control" hx-get="{% url 'shop:search' %}"
           hx-trigger="keyup changed, search"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator">


        <button type="submit" class="btn btn-outline-dark ms-2">Rechercher</button>

    </form>
</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center mb-5">

    {% for name, db_name in categories %}
    <a href="{% url 'shop:all' %}?category={{ db_name }}" class="btn btn-outline-primary">{{ name }}</a>
    {% endfor %}

</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center mb-5">

    <div class="col">

        <a href="{% url 'shop:all' %}" class="btn btn-outline-primary">Supprimer les filtres</a>
    </div>

</div>

<div id="search-results">
{% include 'shop/includes/search.html' %}
</div>

{% endblock %}

docollective/shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block title %}Panier{% endblock %}


{% block body %}

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

    <div class="col mb-5">
        <div class="text-center">
            <h2>Panier de {{ request.user }}</h2>


        </div>
    </div>
</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    {% if request.user.cart %}

    <form method="POST" action="{% url 'shop:delete-garments' %}">
        {% csrf_token %}
        {{ forms.management_form }}
        {% for form in forms %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{ form.instance.garment.pics_1.url }}"/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ form.instance.garment.description }}</h5>
                        <!-- Product price-->
                        {{ form.instance.garment.price }} € <br>

                        <!-- Product state-->
                        {{ form.instance.garment.get_state_display }} <br>
                        <!-- Product size-->
                        Taille {{ form.instance.garment.size }}<br>
                        <!-- Product year-->
                        Année {{ form.instance.garment.garment_year }}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                    {{ form.as_p }}
                </div>
            </div>
        </div>

        {% endfor %}
        <button type="submit">Supprimer du panier</button>
    </form>

    <form action="{% url 'shop:delete-cart' %}" method="post">
    {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Supprimer le panier</button>


    <a href="{% url 'shop:address-choice' %}" class="btn btn-outline-success">Valider</a>

    {% else %}
    <div class="col mb-5">
        <h3>Votre panier est vide</h3>

    </div>
    {% endif %}

</div>


{% endblock %}

docollective/shop/templates/shop/create-garment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Créer une annonce{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Créer une annonce</h2>

</div>

<div class="row justify-content-center">


    <div class="col mb-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Soumettre</button>
        </form>
    </div>


</div>

{% endblock %}

docollective/shop/templates/shop/garment.html
{% extends 'base.html' %}

{% block title %}{{ garment.description }}{% endblock %}


{% block body %}

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

    <div class="col mb-5">
        <div class="text-center">
            <h2>{{ garment.description }}</h2>
            Vendu par <b>{{ garment.user.username }}</b>

        </div>
    </div>
</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="{{ garment.pics_1.url }}"/>
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ garment.description }}</h5>
                    <!-- Product price-->
                    {{ garment.price }} € <br>

                    <!-- Product state-->
                    {{ garment.get_state_display }} <br>
                    <!-- Product size-->
                    Taille {{ garment.size }}<br>
                    <!-- Product year-->
                    Année {{ garment.garment_year }}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center">
                    {% if request.user != garment.user %}
                    <form method="post" action="{% url 'shop:add-to-cart' pk=garment.pk %}">
                        {% csrf_token %}
                        <input type="submit" value="Echanger" class="btn btn-outline-dark mt-auto">

                    </form>
                    {% else %}
                    <a href="{% url 'shop:delete-garment' pk=garment.pk %}" class="btn btn-outline-danger">Supprimer</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>


</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

    <div class="col mb-5">
        <div class="text-center">
            Réf annonce : {{ garment.reference }}

            {% if messages %}

            {% for message in messages %}
            <h5 style="color: red;">{{ message }}</h5>
            {% endfor %}

            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

docollective/shop/templates/shop/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Derniers vêtements mis en ligne</h2>

</div>

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

    {% for garment in garments %}
    <div class="col mb-5">

        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="{{ garment.pics_1.url }}"/>
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ garment.description }}</h5>
                    <!-- Product price-->
                    {{ garment.price }} € <br>

                    <!-- Product state-->
                    {{ garment.get_state_display }} <br>
                    <!-- Product size-->
                    Taille {{ garment.size }}<br>
                    <!-- Product year-->
                    Année {{ garment.garment_year }}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                            href="{% url 'shop:detail' slug=garment.slug pk=garment.pk %}">Détail</a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock %}