docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/sav/models.py
from django.db import models
from uuid import uuid4

from django.urls import reverse

from docollective.settings import AUTH_USER_MODEL
from ckeditor.fields import RichTextField


class Ticket(models.Model):
    reference = models.CharField(max_length=36, default=uuid4)
    subject = models.CharField(max_length=200, verbose_name="Objet")
    closed = models.BooleanField(default=False)
    user = models.ForeignKey(AUTH_USER_MODEL, verbose_name="Utilisateur", on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="Publication", auto_now_add=True)

    def __str__(self):
        return f"{self.date} {self.subject} {self.closed}"

    def get_absolute_url(self):
        return reverse(viewname="sav:ticket", kwargs={"pk": self.pk})

    @property
    def messages_count(self):
        return Message.objects.filter(ticket=self).count()


class Message(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, verbose_name="Utilisateur", on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, verbose_name="Ticket")
    message = RichTextField(verbose_name="Message")
    date = models.DateTimeField(verbose_name="Publication", auto_now_add=True)

    def __str__(self):
        return f"{self.user} {self.ticket} {self.date}"

docollective/sav/forms.py
from django import forms

from sav.models import Message


class MessageForm(forms.ModelForm):
    subject = forms.CharField(label="Objet", help_text="Merci de donner un maximum d'informations.", max_length=200)

    class Meta:
        model = Message
        fields = ["subject", "message"]


class ResponseForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["message"]

docollective/sav/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.http import require_POST
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.db import transaction

from .forms import MessageForm, ResponseForm
from .models import Ticket, Message


@login_required
def new_ticket(request):
    """
      Creates a new ticket and message from a user submission.

      This view handles the creation of a new support ticket. On POST request with valid form data,
      it creates a ticket and an associated message, then redirects to the same page with an
      information message. For GET requests, it displays the message form.

      Args:
      request (HttpRequest): The request object, containing user and form data.

      Returns:
      HttpResponse: Renders the new ticket creation page or redirects after form submission.
      """
    user = request.user

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                ticket = Ticket.objects.create(user=user, subject=form.cleaned_data["subject"])
                form.instance.user = user
                form.instance.ticket = ticket
                form.save()
            messages.add_message(request,
                                 message=f"Ticket {ticket.reference} ouvert. "
                                         f"Vous serez averti par mail lorsqu'une réponse sera donnée",
                                 level=messages.INFO)
            return HttpResponseRedirect(request.path)
    else:
        form = MessageForm()
    return render(request, "sav/new-ticket.html", context={"form": form})


@login_required
def pending_tickets(request):
    user = request.user
    tickets = Ticket.objects.filter(user=user, closed=False)

    return render(request, "sav/pending-tickets.html", context={"tickets": tickets})


@login_required
def closed_tickets(request):
    user = request.user
    tickets = Ticket.objects.filter(user=user, closed=True)

    return render(request, "sav/closed-tickets.html", context={"tickets": tickets})


@login_required
def ticket_view(request, pk):
    """
    Displays and handles responses for a specific support ticket.

    Retrieves the ticket by its primary key (pk). If the user is neither the ticket owner nor a
    superuser, access is denied. On a POST request with valid form data, it adds a response to the
    ticket and redirects to the ticket page. For GET requests, it displays the ticket details and
    response form.

    Args:
    request (HttpRequest): The request object, containing user data and form submissions.
    pk (int): Primary key of the ticket to be viewed.

    Returns:
    HttpResponse: Renders the ticket details page or redirects after a response is submitted.
    """
    user = request.user
    ticket = get_object_or_404(Ticket, pk=pk)
    if user != ticket.user and not user.is_superuser:
        raise PermissionDenied()

    ticket_messages = Message.objects.filter(ticket=ticket)

    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid():
            form.instance.user = user
            form.instance.ticket = ticket
            form.save()
            return redirect(ticket)
    else:
        form = ResponseForm()
    return render(request, "sav/ticket.html", context={"ticket": ticket,
                                                       "messages": ticket_messages, "form": form})


@user_passes_test(lambda user: user.is_superuser)
def tickets_admin_view(request):
    tickets = Ticket.objects.filter(closed=False)
    return render(request, "sav/tickets-admin.html", context={"tickets": tickets})


@login_required
@require_POST
def close_ticket(request, pk):
    """
     Closes a specified support ticket.

     Only allows the ticket's owner or a superuser to close the ticket. Retrieves the ticket
     by its primary key (pk) and sets its status to closed. Redirects to the index page after closure.

     Args:
     request (HttpRequest): The request object containing user data.
     pk (int): Primary key of the ticket to be closed.

     Returns:
     HttpResponseRedirect: Redirects to the index page after closing the ticket.
     """
    user = request.user
    ticket = Ticket.objects.get(pk=pk)
    if user != ticket.user and not user.is_superuser:
        raise PermissionDenied()
    ticket.closed = True
    ticket.save()
    return redirect("index")

docollective/sav/templates/sav/closed-tickets.html
{% extends 'base.html' %}

{% block title %}Tickets fermés{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Tickets clôturés</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">


        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Objet</th>
                <th scope="col">Messages</th>

            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
            <tr>
                <th scope="row">
                    <a href="{% url 'sav:ticket' pk=ticket.pk %}">
                        {{ ticket.date }}
                    </a>
                </th>
                <td>{{ ticket.subject }}</td>
                <td>{{ ticket.messages_count }}</td>

            </tr>

            </tbody>
            {% endfor %}
        </table>


    </div>


</div>

{% endblock %}

docollective/sav/templates/sav/new-ticket.html
{% extends 'base.html' %}

{% block title %}Nouveau ticket{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Nouveau ticket</h2>

</div>

<div class="row justify-content-center">


    <div class="col-6 mb-5">
        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}

            <input type="submit" value="Soumettre" class="btn btn-outline-success">
        </form>

        {% if messages %}

            {% for message in messages %}

            {{ message }}
            {% endfor %}

        {% endif %}

    </div>


</div>

{% endblock %}

docollective/sav/templates/sav/pending-tickets.html
{% extends 'base.html' %}

{% block title %}Tickets en cours{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Tickets en cours</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">


        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Objet</th>
                <th scope="col">Messages</th>

            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
            <tr>
                <th scope="row">

                    <a href="{% url 'sav:ticket' pk=ticket.pk %}">{{ ticket.date }}</a>

                </th>
                <td>{{ ticket.subject }}</td>
                <td>{{ ticket.messages_count }}</td>

            </tr>

            </tbody>
            {% endfor %}
        </table>


    </div>


</div>

{% endblock %}

docollective/sav/templates/sav/ticket.html
{% extends 'base.html' %}

{% block title %}{{ ticket.objet }}{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">{{ ticket.subject }}</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">

        <!--
            Message par message dans une card
            -->
        {% for message in messages %}
        <div class="card">
            <div class="card-header">
                {{ message.user }}
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ message.message|safe }}</p>
                    <footer class="blockquote-footer"><cite title="Source Title">{{ message.date }}</cite>
                    </footer>
                </blockquote>
            </div>
        </div>

        {% endfor %}


    </div>

</div>

<div class="row justify-content-center mb-5">
    <div class="col-6">
        <!--

           Formulaire de réponse limité à l'utilisateur à qui appartient le ticket et aux admins
           -->
        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Envoyer" class="btn btn-outline-success">
        </form>
    </div>
</div>
{% if ticket.closed == False %}
<div class="row justify-content-center">
    <div class="col mb-5">
        <form method="post" action="{% url 'sav:close' pk=ticket.pk %}">
            {% csrf_token %}
            <input type="submit" value="Clôturer le ticket" class="btn btn-success">

        </form>

    </div>


</div>
{% endif %}
{% endblock %}

docollective/sav/templates/sav/tickets-admin.html
{% extends 'base.html' %}

{% block title %}Tickets en attente{% endblock %}


{% block body %}

<div class="row mb-5">
    <h2 class="text-center">Tickets en attente</h2>

</div>


<div class="row justify-content-center">


    <div class="col mb-5">


        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Utilisateur</th>
                <th scope="col">Date</th>
                <th scope="col">Objet</th>

            </tr>
            </thead>
            {% for ticket in tickets %}
            <tbody>

            <tr>
                <th scope="row">
                <a href="{% url 'sav:ticket' pk=ticket.pk %}">{{ ticket.user }}</a>

                </th>
                <td>{{ ticket.date }}</td>
                <td>{{ ticket.subject }}</td>

            </tr>

            </tbody>
            {% endfor %}
        </table>


    </div>


</div>

{% endblock %}