docollective/accounts/urls.py
from django.urls import path
from .views import signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, CreateAddress, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('create-address/', CreateAddress.as_view(), name="create-address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete")
]

docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/accounts/models.py
import iso3166
from django.contrib import messages
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models import Q

from shop.models import SIZES, Color, Garment, Cart, Order

TYPE_USER = [("h", "Homme"), ("f", "Femme"), ("nr", "Non renseigné")]


class ExChangerManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password, **kwargs):
        if not email:
            raise ValueError("email obligatoire")
        user = self.model(email=self.normalize_email(email), username=username, first_name=first_name,
                          last_name=last_name, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, first_name, last_name, password, **kwargs):
        user = self.create_user(email, username, first_name, last_name, password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        return user


class ExChanger(AbstractUser):
    email = models.EmailField(unique=True)
    type = models.CharField(max_length=10, verbose_name="Sexe", choices=TYPE_USER)
    upper_size = models.CharField(verbose_name="Taille haut du corps", choices=SIZES, max_length=10, blank=True)
    lower_size = models.CharField(verbose_name="Taille bas du corps", choices=SIZES, max_length=10, blank=True)
    foot_size = models.CharField(verbose_name="Pointure", choices=SIZES, max_length=10, blank=True)
    favorite_color = models.ForeignKey(to=Color, on_delete=models.SET_NULL, verbose_name="Couleur favorite",
                                       null=True, blank=True)

    REQUIRED_FIELDS = ["username", "first_name", "last_name"]
    USERNAME_FIELD = "email"

    objects = ExChangerManager()

    @property
    def number_adresses(self):
        number_adresses = ExChangerAdresses.objects.filter(user=self).count()
        return number_adresses

    @property
    def upper_size_property(self):
        return self.upper_size or "nc"

    @property
    def lower_size_property(self):
        return self.lower_size or "nc"

    @property
    def foot_size_property(self):
        return self.foot_size or "nc"

    @property
    def favorite_color_property(self):
        return self.favorite_color.name if self.favorite_color else "nc"

    def recommendations(self, size, category):
        """
            Generates a query for garment recommendations based on the user's preferences.

            This method filters garments that match the given size and category, are active,
            correspond to the user's type, and either contain or are associated with the user's
            favorite color.

            Args:
            size (str): The size of the garment.
            category (str): The category of the garment.

            Returns:
            QuerySet: A QuerySet of garment objects that meet the criteria.
            """
        query = Garment.objects.filter(
            Q(size=size), Q(activate=True), Q(type=self.type), Q(category=category),
            Q(description__icontains=self.favorite_color_property) | Q(
                color__name__icontains=self.favorite_color_property)
        )
        return query

    def add_to_cart(self, request, garment):
        """
           Adds a specified garment to the user's cart if it's not already in any cart.

           First checks if the garment is already in the user's cart, then checks if it is
           in any cart. If not in any cart, the garment is added to the user's cart.

           Args:
           request (HttpRequest): The HttpRequest object.
           garment (Garment): The Garment object to add to the cart.

           Returns:
           bool: True if the garment is successfully added, False otherwise.
           """
        cart, _ = Cart.objects.get_or_create(user=self)

        if cart.orders.filter(garment__id=garment.id).exists():
            messages.add_message(request, messages.WARNING, f"{garment.description} est déjà dans votre panier")
            return False

        elif Cart.objects.filter(orders__garment__id=garment.id).exists():
            messages.add_message(request, messages.WARNING, f"{garment.description} est déjà dans un panier")
            return False

        else:
            order = Order.objects.create(user=self, garment=garment)
            cart.orders.add(order)

            return True

    def _update_to_false_all_user_addresses(self):
        self.adresses.filter(default=True).update(default=False)

    def _update_to_true_address(self, pk):
        return self.adresses.filter(pk=pk).update(default=True)

    def update_default_address(self, pk):
        """
            Updates the default address of the user.

            Sets all addresses of the user to non-default and then updates the specified address
            to be the default one.

            Args:
            pk (int): The primary key of the address to be set as default.

            Returns:
            int: The number of records affected by the update operation.
            """
        self._update_to_false_all_user_addresses()
        return self._update_to_true_address(pk)


class ExChangerAdresses(models.Model):
    user: ExChanger = models.ForeignKey(to=ExChanger, on_delete=models.CASCADE, verbose_name="Utilisateur",
                                        related_name="adresses")
    name = models.CharField(max_length=200, verbose_name="Nom de l'adresse")
    address_1 = models.CharField(max_length=1024, help_text="Voirie, numéro de rue", verbose_name="Adresse 1")
    address_2 = models.CharField(max_length=1024, help_text="Bât, étage, lieu-dit", verbose_name="Adresse 2",
                                 blank=True)
    city = models.CharField(max_length=1024, verbose_name="Commune")
    zip_code = models.CharField(max_length=32, verbose_name="Code Postal")
    country = models.CharField(max_length=2, choices=[(c.alpha2.lower(), c.name) for c in iso3166.countries])
    default = models.BooleanField(default=False, verbose_name="Défaut")

    class Meta:
        verbose_name = "Adresse"

    def __str__(self):
        return f"{self.user} - {self.name}"

docollective/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import ExChangerSignupForm
from .models import ExChangerAdresses

from verify_email.email_handler import send_verification_email


def signup(request):
    if request.method == "POST":
        form = ExChangerSignupForm(request.POST)
        if form.is_valid():
            inactive_user = send_verification_email(request, form)
            return redirect("index")
        # Sans le else j'ai un formulaire vide si pas valide
    else:
        form = ExChangerSignupForm()
    return render(request, "accounts/signup.html", context={"form": form})


class ExChangerLogin(LoginView):
    template_name = "accounts/login.html"
    next_page = reverse_lazy("index")


def exchanger_logout(request):
    logout(request)
    return redirect("index")


@login_required
def exchanger_profile(request):
    user = request.user
    try:
        default_adresse = user.adresses.get(user=user, default=True)
    except ObjectDoesNotExist:
        default_adresse = None

    adresses = user.adresses.filter(user=user, default=False)

    return render(request, "accounts/profile.html", context={"user": user,
                                                             "default_adresse": default_adresse,
                                                             "adresses": adresses})


def default_address_view(request, pk):
    user = request.user

    # current_address = user.adresses.get(user=user, default=True)
    # current_address.default = False
    # current_address.save()
    #
    # new_address = user.adresses.get(pk=pk)
    # new_address.default = True
    # new_address.save()
    # Mettre à jour l'adresse actuelle par défaut
    user.adresses.filter(default=True).update(default=False)

    # Définir la nouvelle adresse comme adresse par défaut
    updated_rows = user.adresses.filter(pk=pk).update(default=True)

    # Vérifier si l'adresse avec `pk=pk` a été mise à jour
    if not updated_rows:
        # Gérer l'erreur ici, par exemple en retournant une réponse d'erreur
        return HttpResponse("Adresse non trouvée", status=404)

    if request.GET.get("redirect") == "validate":
        return redirect("shop:address-choice")

    return redirect("accounts:profile")


class CreateAddress(LoginRequiredMixin, CreateView):
    model = ExChangerAdresses
    template_name = "accounts/create-address.html"
    fields = ["name", "address_1", "address_2", "city", "zip_code", "country"]
    success_url = reverse_lazy("shop:address-choice")

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.request.user.adresses.filter(default=True).update(default=False)
        form.instance.default = True

        return super().form_valid(form)

docollective/accounts/views/password.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


class ExchangerChangePassword(PasswordChangeView):
    template_name = "password/change-form.html"
    success_url = reverse_lazy("accounts:change-done")


class ExchangerPasswordDone(PasswordChangeDoneView):
    template_name = "password/change-done.html"


class ExchangerResetPassword(PasswordResetView):
    template_name = "password/reset.html"
    success_url = reverse_lazy("accounts:reset-done")
    email_template_name = "password/reset-email.html"


class ExchangerResetDone(PasswordResetDoneView):
    template_name = "password/reset-done.html"


class ExchangerResetConfirm(PasswordResetConfirmView):
    template_name = "password/reset-confirm.html"
    success_url = reverse_lazy("accounts:reset-complete")


class ExchangerResetComplete(PasswordResetCompleteView):
    template_name = "password/reset-complete.html"

docollective/accounts/views/user.py
from smtplib import SMTPAuthenticationError

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from accounts.forms import ExChangerSignupForm
from accounts.models import ExChangerAdresses

from verify_email.email_handler import send_verification_email

import logging

logger = logging.getLogger(__name__)


def signup(request):
    """
        Processes the user signup request.

        If the request is POST, it attempts to create a new user using the ExChangerSignupForm.
        Upon successful validation, it tries to send a verification email. If there's an SMTP
        authentication error, it logs the error and saves the form without sending the email.
        After handling the POST request, it redirects to the index page. For non-POST requests,
        it simply displays the signup form.

        Args:
        request (HttpRequest): The HttpRequest object representing the current request.

        Returns:
        HttpResponse: Renders the signup page with the signup form.
        """
    if request.method == "POST":
        form = ExChangerSignupForm(request.POST)
        if form.is_valid():
            try:
                inactive_user = send_verification_email(request, form)
            except SMTPAuthenticationError:
                logger.critical(f"Smtp not running for {form.instance.email}")
                form.save()
            return redirect("index")

    else:
        form = ExChangerSignupForm()
    return render(request, "accounts/signup.html", context={"form": form})


class ExChangerLogin(LoginView):
    template_name = "accounts/login.html"
    next_page = reverse_lazy("index")


def exchanger_logout(request):
    logout(request)
    return redirect("index")


@login_required
def exchanger_profile(request):
    user = request.user
    try:
        default_adresse = user.adresses.get(user=user, default=True)
    except ObjectDoesNotExist:
        default_adresse = None

    adresses = user.adresses.filter(user=user, default=False)

    return render(request, "accounts/profile.html", context={"user": user,
                                                             "default_adresse": default_adresse,
                                                             "adresses": adresses})


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = "accounts/update-profile.html"
    fields = ["upper_size", "lower_size", "foot_size", "favorite_color"]
    success_url = reverse_lazy("accounts:profile")


def default_address_view(request, pk):
    """
      Sets a user's address as default and redirects based on the request.

      Updates the default address of the user to the address specified by pk. If the address
      is not found, returns a 404 response. Redirects to either the address choice or profile
      page based on the request's redirect parameter.

      Args:
      request (HttpRequest): The request object.
      pk (int): Primary key of the address to set as default.

      Returns:
      HttpResponse or HttpResponseRedirect: 404 response or a redirect response.
      """
    user = request.user

    updated_rows = user.update_default_address(pk)

    if not updated_rows:
        return HttpResponse("Adresse non trouvée", status=404)

    return redirect("shop:address-choice") if request.GET.get("redirect") == "validate" else redirect(
        "accounts:profile")


class CreateAddress(LoginRequiredMixin, CreateView):
    model = ExChangerAdresses
    template_name = "accounts/create-address.html"
    fields = ["name", "address_1", "address_2", "city", "zip_code", "country"]
    success_url = reverse_lazy("shop:address-choice")

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.request.user.adresses.filter(default=True).update(default=False)
        form.instance.default = True

        return super().form_valid(form)

docollective/accounts/templates/accounts/create-address.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Créer une adresse{% endblock %}


{% block body %}
<div class="row">
    <div class="col">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Envoyer" class="btn btn-outline-primary">

        </form>
    </div>
</div>
{% endblock %}

docollective/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}


{% block body %}
<div class="row">
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Envoyer" class="btn btn-outline-primary">

        </form>
    </div>
    <div class="col-6">
<div class="text-center">
<img src="{% static 'assets/signup_compress.jpg' %}" class="img-fluid">
</div>
    </div>
</div>
{% endblock %}

docollective/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Profil{% endblock %}


{% block body %}
<div class="row">
    <div class="col-4">

        <div class="text-center">
            <div class="card mx-auto mb-5" style="width: 18rem;">
                <div class="card-header">
                    Profil
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Email : {{ user.email }}</li>
                    <li class="list-group-item">Pseudo : {{ user.username }}</li>
                    <li class="list-group-item">Nom : {{ user.first_name }}</li>
                    <li class="list-group-item">Prénom : {{ user.last_name }}</li>
                    <li class="list-group-item">Taille Haut : {{ user.upper_size_property }}</li>
                    <li class="list-group-item">Taille Bas : {{ user.lower_size_property }}</li>
                    <li class="list-group-item">Pointure : {{ user.foot_size_property }}</li>
                    <li class="list-group-item">Couleur favorite : {{ user.favorite_color_property }}</li>
                </ul>
            </div>
            <a href="{% url 'accounts:profile-update' pk=user.pk %}" class="btn btn-outline-success">Mettre à jour mes
                informations</a>
        </div>


    </div>

    <div class="col-4">

        <div class="text-center">
            {% if default_adresse %}
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    Adresse par défaut
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ default_adresse.name }}</li>
                    <li class="list-group-item">{{ default_adresse.address_1 }}</li>
                    {% if default_adresse.address_2 %}
                    <li class="list-group-item">{{ default_adresse.address_2 }}</li>
                    {% endif %}
                    <li class="list-group-item">{{ default_adresse.zip_code }} - {{ default_adresse.city }}</li>
                    <li class="list-group-item">{{ default_adresse.get_country_display }}</li>
                </ul>
            </div>


            {% else %}
            Pas d'adresse(s) enregistrées
            {% endif %}


        </div>

    </div>
    <div class="col-4">

        <div class="text-center">
            <a href="{% url 'accounts:change-password' %}" class="btn btn-danger">Modifier son mot de passe</a>


        </div>

    </div>

</div>
<div class="row" style="margin-top: 20px;">

    <div class="col">

        <div class="text-center">
            <p class="d-inline-flex gap-1">
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Autres adresses
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                {% for adresse in adresses %}
                <div class="card card-body mx-auto" style="margin-bottom: 20px; max-width: 300px;">
                    <!--
                    Toutes les adresses False
                    -->


                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ adresse.name }}</li>
                        <li class="list-group-item">{{ adresse.address_1 }}</li>
                        {% if adresse.address_2 %}
                        <li class="list-group-item">{{ adresse.address_2 }}</li>
                        {% endif %}
                        <li class="list-group-item">{{ adresse.zip_code }} - {{ default_adresse.city }}</li>
                        <li class="list-group-item">{{ adresse.get_country_display }}</li>
                    </ul>

                    <form action="{% url 'accounts:default_address' pk=adresse.pk %}" method="post">

                        {% csrf_token %}
                        <input type="submit" value="Définir" class="btn btn-outline-info">

                    </form>


                </div>
                {% endfor %}
            </div>

        </div>

    </div>


</div>
{% endblock %}

docollective/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Inscription{% endblock %}


{% block body %}
<div class="row">
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Envoyer" class="btn btn-outline-primary">

        </form>
    </div>
    <div class="col-6">
<div class="text-center">
<img src="{% static 'assets/signup_compress.jpg' %}" class="img-fluid">
</div>
    </div>
</div>
{% endblock %}

docollective/accounts/templates/accounts/update-profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Mettre à jour le profil{% endblock %}


{% block body %}
<div class="row">
    <div class="col-6">
        <form method="post" class="mb-5">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Mettre à jour" class="btn btn-outline-primary">

        </form>

    </div>
    <div class="col-6">
        <div class="text-center">
            <img src="{% static 'assets/signup_compress.jpg' %}" class="img-fluid">
        </div>
    </div>
</div>
{% endblock %}