docollective/accounts/urls.py
from django.urls import path
from .views import signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, CreateAddress, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('create-address/', CreateAddress.as_view(), name="create-address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete")
]

docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/shop/urls.py
from django.urls import path
from .views import detail_view, add_to_cart, cart_view, delete_garments_cart, delete_cart, CreateGarment, all_garments, \
    DeleteGarment, my_shop_view, validate_cart_view, address_choice_view, admin_deal_validation_view, recommendations_view, \
    admin_advert_validation_view, search_results_view

app_name = "shop"
urlpatterns = [
    path("garment/<str:slug>/<int:pk>/", detail_view, name="detail"),
    path("add-to-cart/<int:pk>/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("address-choice/", address_choice_view, name="address-choice"),
    path("validate-cart/", validate_cart_view, name="validate-cart"),
    path("delete-garments/", delete_garments_cart, name="delete-garments"),
    path("delete-cart/", delete_cart, name="delete-cart"),
    path("create-garment/", CreateGarment.as_view(), name="create"),
    path("delete-garment/<int:pk>/", DeleteGarment.as_view(), name="delete-garment"),
    path("all/", all_garments, name="all"),
    path("search/", search_results_view, name="search"),
    path("recommendations/", recommendations_view, name="recommendations"),
    path("my-shop/", my_shop_view, name="my-shop"),
    path("admin-validation/", admin_deal_validation_view, name="admin-validation"),
    path("admin-ad-validation/", admin_advert_validation_view, name="admin-advert"),
]

docollective/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>

</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'index' %}">Docollective</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Déconnexion</a>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Inscription</a>
                </li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Connexion</a>
                </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown2" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Mon compte</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profil</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'shop:create' %}">Mettre en vente</a></li>
                        <li><a class="dropdown-item" href="{% url 'shop:my-shop' %}">Mes commandes / ventes</a></li>
                    </ul>
                </li>
                {% endif %}


                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Magasin</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:create' %}">Mettre en vente</a></li>
                        <li><a class="dropdown-item" href="{% url 'shop:all' %}">Tous les articles</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'shop:recommendations' %}">Recommandations</a></li>
                        {% endif %}
                    </ul>
                </li>


                <!--SAV -->
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown3" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Assistance</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
                        <li><a class="dropdown-item" href="{% url 'sav:new-ticket' %}">Nouveau ticket</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'sav:pending-tickets' %}">Tickets en cours</a></li>
                        <li><a class="dropdown-item" href="{% url 'sav:closed-tickets' %}">Historique</a></li>
                    </ul>
                </li>

                <!-- end SAV -->

                {% if request.user.is_superuser %}
                <!-- Admin Panel -->

                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown4" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Tâches en attente</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown4">
                        <li><a class="dropdown-item" href="{% url 'shop:admin-validation' %}">Echanges en attente</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'shop:admin-advert' %}">Annonces en attente</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'sav:admin-tickets' %}">Tickets en attente</a></li>

                    </ul>
                </li>

                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration
                    Django</a></li>

                <!--end Admin Panel -->
                {% endif %}
            </ul>
            <form class="d-flex">
                <a href="{% url 'shop:cart' %}" class="btn btn-outline-dark">
                    <i class="bi-cart-fill me-1"></i>
                    Panier
                    {% if request.user.cart %}
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ request.user.cart.orders.all.count }}</span>
                    {% else %}
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    {% endif %}
                </a>
            </form>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-light bg-gradient py-5 border border-secondary">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder">DoCollective</h1>
            <p class="lead fw-normal text-black-50 mb-0">Markeplace pour vos vêtements</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">

        {% block body %}{% endblock %}

    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Docollective 2023</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

docollective/templates/base_shop.html
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Fancy Product</h5>
                            <!-- Product price-->
                            $40.00 - $80.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>